### PR TITLE
Add support for i18n and remove generated files

### PR DESCRIPTION
**Pull request by Tommytrg**
Add support for i18n using [rosetta](https://www.npmjs.com/package/rosetta) library, which supposes the following changes in the Radon class API:
   - Accept a new argument in the constructor: `locale: Locale`
   - Add `setLocale(locale: Locale): void` method to allow change the current locale.
   - Remove generated files
   - Add npm information such as repository
   - Export library types
   
Currently, the library accepts 'en' and 'es' (which doesn't include translations) as valid locales, but any other can be added, creating a new file in the `./locales/` folder,

This PR also bump version to 0.8.2.

### CODE REVIEW

**Comment by aesedepece** [comment]
Awesome. Once this is merged, I'll setup the integration with Crowdin so this also shows up in the Sheikah project there.

**Comment by aesedepece** [comment]
Oooops, I just saw that the location files are in `.ts` format. Is it too much of a hassle to make them adhere to [one of the formats currently supported by Crowdin][formats]?

[formats]: https://support.crowdin.com/supported-formats/

**Comment by Tommytrg** [comment]
I've updated the location files to be `.json` which is a format supported by Crowdin

**Review by aesedepece — APPROVED** [review]
Looks good to me!

**Pull request merged**
